In [1]:
import numpy as np

#random 5x5 ndarray
X = np.random.rand(5, 5)  # values between 0 and 1
print("Original 5x5 Array (X):\n", X)

#Normalizing x
X_normalized = (X - X.mean()) / X.std()
print("\nNormalized Array (X_normalized):\n", X_normalized)

#Save normalized array
np.save("X_normalized.npy", X_normalized)

numbers = np.arange(1, 101)         # integers from 1 to 100
squares = numbers ** 2              # squares
A = squares.reshape(10, 10)         # reshape into 10x10 matrix
print("\n10x10 Array of Squares (A):\n", A)

#elements divisible by 3
div_by_3 = A[A % 3 == 0]
print("\nElements divisible by 3:\n", div_by_3)

#save
np.save("div_by_3.npy", div_by_3)

Original 5x5 Array (X):
 [[0.85233855 0.85435196 0.56916817 0.65785926 0.42271385]
 [0.81762106 0.52414217 0.42672334 0.89013667 0.10030047]
 [0.95930874 0.24336991 0.53324726 0.9383659  0.8231944 ]
 [0.70812892 0.4268814  0.4557     0.09263327 0.43986161]
 [0.43474525 0.87385577 0.95051179 0.39531512 0.94996744]]

Normalized Array (X_normalized):
 [[ 0.90574982  0.91338907 -0.16864949  0.16786045 -0.72432348]
 [ 0.77402542 -0.33948622 -0.70911074  1.04916269 -1.94761775]
 [ 1.31161394 -1.40478659 -0.30493984  1.23215302  0.79517167]
 [ 0.3585926  -0.70851101 -0.59916809 -1.97670849 -0.65926178]
 [-0.67867415  0.98739003  1.27823673 -0.82827917  1.27617135]]

10x10 Array of Squares (A):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  